name: 'Install Rust Components'
description: 'A reusable GitHub Action to install rustc, rustfmt, and rust-std'

runs:
  using: 'composite'
  steps:
    - name: Install stable toolchain
      shell: bash
      run: rustup toolchain install stable --component=rustfmt

    - name: Install x86_64-unknown-linux-musl
      shell: bash
      run: rustup target add x86_64-unknown-linux-musl

    - name: Verify installation
      shell: bash
      run: |
        rustc --version
        rustfmt --version
        rustup component list --installed
