version: '3'
services:
  prometheus:
    image: prom/prometheus@sha256:e4254400b85610324913f0dc4acf92603d9984e7519414c5a12811aa6146acc3
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090
  osc-cost:
    image: outscale/osc-cost:v0.8.0@sha256:611690879da952d1316cfe80f3fd9e255fb6ca2f11d32617ef2a26519467f350
    networks:
      - localprom
    ports:
      - 8080:8080
    # Replace with your AK/SK
    # environment:
     # OSC_ACCESS_KEY: OSC_ACCESS_KEY
     # OSC_SECRET_KEY: OSC_SECRET_KEY
     # OSC_REGION: OSC_REGION     
  node-exporter:
    image: prom/node-exporter@sha256:e9cff4fc67b1818f8c97adb115b9f12c9a54b533de86765d4a0effc01b357205
    networks:
      - localprom
    ports:
      - 9100:9100
networks:
  localprom:
    driver: bridge
