name: pull-request

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: write
    
jobs:
  reuse-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Reuse specification test
        run: make reuse-test
  format-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Stable Rust with rustfmt
        uses: ./.github/actions/install_toolchain
      - name: Check code format
        run: make format-test
        env:
          RUSTFLAGS: "-Dwarnings"
  cargo-test:
    environment: eu-west-2
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Stable Rust with rustfmt
        uses: ./.github/actions/install_toolchain
      - name: Run tests
        run: make cargo-test
  cargo-clippy:
    environment: eu-west-2
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Stable Rust with rustfmt
        uses: ./.github/actions/install_toolchain
      - name: Run tests
        run: make cargo-clippy
  integration-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install musl-tools
        run: sudo apt update -y && sudo apt install musl-tools -y
      - name: Stable Rust with rustfmt
        uses: ./.github/actions/install_toolchain
      - name: Run integration tests
        run: make integration-test
        env:
          OSC_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY }}
          OSC_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY }}
          OSC_REGION: ${{ secrets.OSC_REGION }}
