name: release-docker-image
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set release_tag
      run: |
        echo 'RELEASE_TAG<<EOF' >> $GITHUB_ENV
        echo "${GITHUB_REF:10}" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Docker login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY_REPO
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_REPO: ${{ secrets.DOCKER_REGISTRY_REPO }}
    - name: build and push docker image
      run: |
        make docker-build
        make docker-push
        docker image prune -a -f
      env:
        IMG: ${{ secrets.DOCKER_REGISTRY_REPO }}/cluster-api-outscale-controllers:${{ env.RELEASE_TAG }}
        DOCKER_BUILDKIT: 1